#!/bin/bash

function get_total() {
	total=$(find ./downloads -name "*.st" | wc -l)
	total=$((total + 0))

	echo $total
}

function download_vid() {
	count=$(cat ./start.txt)
	if [[ -z "$count" ]]; then
		count=1
	else
		count=$(echo $count | sed 's/^0*//')
	fi

	while IFS='' read -r line || [[ -n "$line" ]]; do
		dfile="downloads/videoplayback_${count}.mp4"
		
		if [[ -f "${dfile}.st" ]]; then
			axel -a -n 16 -o $dfile $line
		else if [[ ! -f $dfile ]]; then
			axel -a -n 16 -o $dfile $line
		fi
		count=$((count + 1))
	fi
	done < "$1"
}

mkdir -p downloads/
download_vid list.txt

total=$(get_total)
while [[ $total > 0 ]]; do
	download_vid list.txt

	sleep 1
	total=$(get_total)
done
