#!/bin/bash

function get_total() {
	total=$(find ./downloads -name "*.st" | wc -l)
	total=$((total + 0))

	echo $total
}

function download_vid() {
	while IFS='' read -r line || [[ -n "$line" ]]; do
		# Because the line contains both the link and episode name
		IFS=';' read -r -a array <<< "$line"
		dlink="${array[0]}"
		dfile="downloads/${array[1]}"	# Convert the episode name to corresponding download file
		
		if [[ -f "${dfile}.st" ]]; then
			axel -a -n 10 -o $dfile $dlink
		else if [[ ! -f $dfile ]]; then
			axel -a -n 10 -o $dfile $dlink
		fi
	fi
	done < "$1"
}

mkdir -p downloads/
download_vid axel-list.txt

total=$(get_total)
# @todo test in the next version
# while [[ $total > 0 ]]; do
# 	download_vid axel-list.txt

# 	sleep 1
# 	total=$(get_total)
# done
