#!/bin/bash

mkdir -p downloads/
count=$(cat start.txt)

if [[ -z "$count" ]]; then
	count=1
else
	count=$(echo $count | sed 's/^0*//')
fi

while IFS='' read -r line || [[ -n "$line" ]]; do
	dfile="downloads/videoplayback_${count}.mp4"
	
	if [[ -f "${dfile}.st" ]]; then
		axel -a -n 14 -o $dfile $line
	else if [[ ! -f $dfile ]]; then
		axel -a -n 14 -o $dfile $line
	fi
	count=$((count + 1))
fi
done < "$1"