#!/bin/bash

mkdir -p downloads/
count=$(cat start.txt)

if [[ !$count ]]; then
	count=0
fi
while IFS='' read -r line || [[ -n "$line" ]]; do
	count=$((count + 1))
	dfile="downloads/videoplayback_${count}.mp4"
	
	if [[ -f "${dfile}.st" ]]; then
		axel -a -n 14 -o $dfile $line
	else if [[ ! -f $dfile ]]; then
		axel -a -n 14 -o $dfile $line
	fi

fi
done < "$1"